stages:
  - build
build:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_DEPTH: 1
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  stage: build
  script:
    - "[[ -z \"${CI_COMMIT_TAG}\" ]] && version=\"${CI_COMMIT_SHORT_SHA}\" || version=\"${CI_COMMIT_TAG}\""
    - echo "{\"auths\":{\"${SCW_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${SCW_REGISTRY_USER}" "${SCW_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/odoo"
      --cache=true
      --cache-copy-layers=true
      --dockerfile "${CI_PROJECT_DIR}/odoo/Dockerfile"
      --destination "${SCW_REGISTRY_IMAGE}:${version}"
      --destination "${SCW_REGISTRY_IMAGE}:latest"
  only:
    - main
